services:
  bash:
    entrypoint: bash
    build: ../
    <<: &default
      image: dannyben/snapcrawl
      volumes: [".:/app"]

  snapcrawl:
    <<: *default

  mockserver:
    image: dannyben/alpine-adsf
    volumes: [".:/app"]
    ports: ["3000:3000"]
